name: Bug Report
description: Report a bug or crash in Dark Floor
title: "[BUG] "
labels: [bug]

body:
  - type: input
    id: seed
    attributes:
      label: Seed
      description: The seed that caused the bug
      placeholder: e.g. 81f3ab2c
    validations:
      required: true

  - type: input
    id: floor
    attributes:
      label: Floor
      description: Floor where the bug occurred
      placeholder: e.g. 12
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - Linux
        - macOS
        - Other

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: e.g. 3.11.2

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: What did you do before the bug happened?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
