name: Feature Request
description: Suggest a new feature or system
title: "[FEATURE] "
labels: [enhancement]

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Short description of the feature
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this needed?

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: textarea
    id: impact
    attributes:
      label: Gameplay Impact
