name: Entity Suggestion
description: Propose a new enemy or NPC
title: "[ENTITY] "
labels: [entity, enhancement]

body:
  - type: input
    id: name
    attributes:
      label: Entity Name
    validations:
      required: true

  - type: textarea
    id: behavior
    attributes:
      label: Behavior
      description: What does it do?

  - type: textarea
    id: threat
    attributes:
      label: Threat Profile
      description: How does it kill or pressure the player?

  - type: textarea
    id: counterplay
    attributes:
      label: Counterplay
      description: How can the player survive?

  - type: dropdown
    id: difficulty
    attributes:
      label: Intended Difficulty
      options:
        - Early game
        - Mid game
        - Late game
        - Boss-tier
